# Default values for phoenix-enrollments-api
# This file is in YAML format
# Declared variables to be passed into $/templates files

appName: enrollments-api
namespace: phoenix-qa

image:
  repository: 889859566884.dkr.ecr.us-east-1.amazonaws.com/phoenix-enrollments-api
  tag: qa
  pullPolicy: Always

imagePullSecrets: []

service:
  type: NodePort
  port: 80

ingress:
  external:
    sslRedirect: "false"
    forceSslRedirect: "true"

dns:
  internal: dev.sgp.private.wiley.host
  external: dev.sgp.wiley.host

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

# replicacount has no impact if autoscaling.enabled = true
replicacount: 1
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 85

env_vars:
  data:
    LOG_JSON: "true"
    LOG_MINIMUMLEVEL: Information
    MONGO_DB_NAME: enrollments-api
    MONGO_TLS_CA_FILE_PATH: "/cert/global-bundle.pem"
    USERS_API_BASE_URL: "http://users-api/api/v4/users"
    TRAINING_PROGRAM_API_BASE_URL: "http://contents-api/v4/training-programs"
    COMPANY_API_BASE_URL: "http://company-api/api/v4/organizations"
    OPA_BASE_URL: "http://opa"
    KEYCLOAK_BASE_URL: "https://keycloak.dev.sgp.wiley.host"
    KEYCLOAK_REALM: "phoenix"
    KEYCLOAK_AUDIENCE: "account"
    KEYCLOAK_REQUIRE_METADATA: true
    KAFKA_HOST: b-1.eksnonprodus.rsck18.c20.kafka.us-east-1.amazonaws.com:9092,b-2.eksnonprodus.rsck18.c20.kafka.us-east-1.amazonaws.com:9092
    KAFKA_TOPIC: "ck-phoenix-enrollment"

externalsecrets:
  refreshInterval: 1m
  secretCreationPolicy: Owner
  secretStoreName: eks-nonprod-us-secret-manager
  secretStoreType: ClusterSecretStore
  data:
  - keyValue: dev/eks/phoenix
    nameValue: USERS_API_KEY
    propertyValue: USERS_API_KEY
  - keyValue: dev/eks/phoenix
    nameValue: COMPANY_API_KEY
    propertyValue: COMPANY_API_KEY
  - keyValue: dev/eks/phoenix
    nameValue: MONGO_CONNECTION_STRING
    propertyValue: ENROLLMENTS_API_NONPROD_MONGO_CONNECTION_STRING
  - keyValue: dev/eks/phoenix
    nameValue: API_KEY
    propertyValue: ENROLLMENTS_API_KEY
  - keyValue: dev/eks/phoenix
    nameValue: CONTENTS_API_KEY
    propertyValue: CONTENTS_API_KEY
